/**
 * Main entry point for stratiqai-types-simple
 *
 * Exports:
 * - GraphQL schema
 * - GraphQL operations (queries, mutations, subscriptions)
 * - TypeScript types (generated by GraphQL Code Generator)
 *
 * Note: TypeScript types are generated by running `npm run generate:types`
 * They will be available in './generated/types.js' after code generation.
 */

// Schema export is optional - schema.graphql is not included in the package
// Uncomment if you need schema loading functionality:
// export * from "./schema.js";
export * from "./operations.js";

// Re-export generated types for convenience
// This ensures consumers get type-safe operations
export type * from "./generated/types.js";
 
// Re-export EventBridge interfaces for convenience
export type { S3ObjectCreatedDetailData, S3ObjectCreatedDetail } from "./events/aws.s3/interfaces.js";

// Event sources and detail-types for EventBridge (naming-schema-proposal)
export { EVENT_SOURCES, EVENT_DETAIL_TYPES } from "./events/constants.js";

// AI Query Execution SQS payload types (submit-ai-query, ai-query-execution-worker)
export type { VisionRagInputs, AIQueryExecutionSqsPayload } from "./ai-query-execution/types.js";
